<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "showmi"
 *
 * Auto generated by Extension Builder 2019-10-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Showmi List',
    'description' => 'Show database data as formatted listings',
    'category' => 'plugin',
    'author' => 'Erik Bartoš',
    'author_email' => 'erik.bartos@gmail.com',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.13',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
	'autoload' => [
		'psr-4' => [
			'Mezek\\Showmi\\' => 'Classes'
		],
	],
];
